[supabase]
url = "https://jbfcpaxncwhveusxiimd.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZmNwYXhuY3dodmV1c3hpaW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3MTcwNzEsImV4cCI6MjEwMTI5MzA3MX0.-OxSY6MYbRTix7-6nWAN5v7ANv5Midocrte24U79nx0"