[gserviceaccount]
type = "service_account"
project_id = "miappdrive-504417"
private_key_id = "ee0dee89cb92dfa60c0b484241fd687c2e8ce2c3"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDMlAZyXgDHgIqM
yiuiS90UXghKJoBSXQETyL+CyA3qHWH/m8HgHNPYXrth4OUYWQnXg2PJchHR9k7S
qukcawYICOSzEuyhzyGc0m0+7HYH4oB9oqtewT8hD83aUhVS10xEfT2Kmg6cujgR
0baL8zuf68QB4/xFM0CjGkUslstxgK7oFT61lbdCRAIfYf1chvcNYECyEzwV0tDG
16uTBQsUr+taIf72ECubUoXG+sl+rfWPtGi/WJNHcSTiEw39+5yc3JzfQ0OWYNzf
ReMa8NOdqtis02MLsDJnSMUeEOzCRSn+RIJxAjbLWxpGU4u9QgWlOIdOAB+JYSdA
oAB700tTAgMBAAECggEAGgnfNjBTzhDE0b2rxxj71ytOx81VuOYAjJmZEpbO+pTp
08Rp7VIN/rS0CfW7gxlWINmm2k2MChrdFoBNcmIG3v/uyAIpH0FDaHf6Eq+7KC7C
pvsM798N33HpBBg9gZFIslD0g88u+/DR0SbNost/M9Ao3wq7Ib2vxPLDijTZSSVa
zJA+lZ39ZK7+lojHFtzu0EswzWJzA11BD1DVsijmzZlsRAuFT7WNQ2g66f423XrF
3SGsEIP/QHb4f30KsrLFz6ENPPd9PD98VvFFyLaMswfrlyTny8PgSM39mxUV8CxV
ec+9mOum8iur213MTbTFQzocj6EiNWOTtlsJXJ+EnQKBgQD9vqheoQj4Ow2xAQfw
6qESj0lZDwpCTGygIfYY1FuovPbKXKgjygVMEmb535m9e2gdug/WjYf7wAZJIIQ9
QSUJfIcZsk6kMj39xY65v5pjJqY08mecNVvCQGx3SaSEUgF8oNM6b7Ndka4Yz+W2
yYV/eGkFOUHAG18xx55BkzJofwKBgQDOZX/eKpklBVQEMYGig6qznKQjDNyOIdbe
0pTo0JjQDyJyCxAWdToPThKHN32/ETOqBHWQPXHEZhi/qSSPpvzkCxXhhA/ajdZI
NzR+A/AXUtS+hL6UeEZ5ABNNmOzYO+YlJLCwf9W8HxBk6YLw+MxIy5a5EeoIvs4y
fH9x6wqTLQKBgDZ9zTaVKpH0TJpoeEYafQC5WK0Rd8iJFQLGiE0Iva5c9jq67zjQ
V5bglNCwXhm8+Lz5ihEvT7aWpELsAroM1WFWJsUz74N/bqSi2mW1afhFAoh4ThvT
saLjpudvHy9zVPJorzPrbP95G4QkkVZRrKOVPihrBV22Axlznt7CN58NAoGAEZbC
w9sbe/UtSMIzSvcvh+j0b+w7q30kw45slD6alziC9fcNYuyQixdbKtzGwY6kuXtx
zV3/IP6WY1b1v6w6ZvCu564Kb9SgizzxI0AQqNwtNyM23o41a0BfZMCAhpjsLwQm
bpQmUcbP7dmciA6b0iRPbuwg5qfkCJdlgP7Hwu0CgYB85Ev7/dKgyBnoOVUSZCYz
S8QuxCNFC/LlJtPuVUIvtYH3hIM2pZmMgGHjxK2UJzf33tM0PdzyBTz4Yp8kfs0K
2wtkwfem/yIr34hkcQSw3RVwOzhIyAMkPOCVh82wEXFyN6oV3TwEORPyc7t6kvkH
nG/kF1G9cXOvD9NAKDWkqtw==
-----END PRIVATE KEY-----"""
client_email = "pixel-2@miappdrive-504417.iam.gserviceaccount.com"
client_id = "117547203433763453044"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/pixel-2%40miappdrive-504417.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
gdrive_folder_id = "https://drive.google.com/drive/u/0/folders/1beJyyFASER_8RZ1PLemsdqoBR_PfPiXP"